kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mystorageclaim
  annotations:
    volume.beta.kubernetes.io/storage-class: "ministorage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
